<?php
// certificate-pdf.php
session_start();

// User must be logged in
if (!isset($_SESSION['cid'])) {
    header("Location: login.php");
    exit;
}

$cid = (string)$_SESSION['cid'];

// ------------------------------------------
// 1) Validate input
// ------------------------------------------
$accountNoParam = $_GET['acc'] ?? '';
if ($accountNoParam === '') {
    die("Account number not provided.");
}

// ------------------------------------------
// 2) DB CONNECTION
// ------------------------------------------
$host     = "localhost";
$user     = "root";
$password = "";
$database = "my_bank";

$conn = new mysqli($host, $user, $password, $database);
if ($conn->connect_error) {
    die("Database connection failed: " . $conn->connect_error);
}

// ------------------------------------------
// 3) Fetch account info
// ------------------------------------------
// Adjust column names if needed to match your DB exactly.
$sql = "SELECT AccountNo, account_name, account_type, Balance 
        FROM accounts
        WHERE CustomerID = ? AND AccountNo = ?
        LIMIT 1";

$stmt = $conn->prepare($sql);
if (!$stmt) {
    die("SQL prepare failed: " . $conn->error);
}
$stmt->bind_param("ss", $cid, $accountNoParam);
$stmt->execute();
$res = $stmt->get_result();

if (!$res || $res->num_rows !== 1) {
    $stmt->close();
    $conn->close();
    die("Account not found.");
}

$row = $res->fetch_assoc();
$stmt->close();
$conn->close();

$accountNo   = $row['AccountNo'];
$accountName = $row['account_name'];
$accountType = $row['account_type'] ?? 'Account';
$balance     = (float)$row['Balance'];

$issueDate  = date('F j, Y');
$branchName = "Main Branch, My Bank";   // adjust if you have branch data in DB

// ------------------------------------------
// 4) Load FPDF
// ------------------------------------------
// Make sure fpdf.php path is correct for your project structure.
require 'fpdf186/fpdf.php';

// ------------------------------------------
// 5) Create PDF
// ------------------------------------------
class CertificatePDF extends FPDF
{
    function Header()
    {
        // Top margin
        $this->SetY(12);

        // Bank name / logo style text
        $this->SetFont('Arial', 'B', 18);
        $this->Cell(0, 8, 'My Bank', 0, 1, 'C');

        $this->Ln(2);
        $this->SetFont('Arial', '', 11);
        // Match HTML: "Official account confirmation"
        $this->Cell(0, 6, 'Official account confirmation', 0, 1, 'C');

        $this->Ln(4);
        // Separator line
        $this->SetDrawColor(0, 0, 0);
        $this->SetLineWidth(0.4);
        $this->Line(20, $this->GetY(), 190, $this->GetY());

        $this->Ln(8);
    }

    function Footer()
    {
        // Position at 1.5 cm from bottom
        $this->SetY(-15);
        $this->SetFont('Arial', 'I', 8);
        $this->Cell(0, 10, 'Generated by My Bank Internet Banking System', 0, 0, 'C');
    }
}

// Create PDF
$pdf = new CertificatePDF();
$pdf->AddPage();
$pdf->SetAutoPageBreak(true, 20);

// ------------------------------------------
// 6) Certificate body (matching HTML format)
// ------------------------------------------

// Title like on the page: "Account Opening Certificate"
$pdf->SetFont('Arial', 'B', 16);
$pdf->Cell(0, 10, 'Account Opening Certificate', 0, 1, 'C');
$pdf->Ln(4);

// Issue date on the right, same info as HTML
$pdf->SetFont('Arial', '', 12);
$pdf->Cell(0, 6, 'Issue Date: ' . $issueDate, 0, 1, 'R');
$pdf->Ln(4);

// Intro text — same sentence as your HTML certificate
$pdf->SetFont('Arial', '', 12);
$intro = sprintf(
    "This is to certify that %s, Customer ID %s, maintains a %s with My Bank at %s.",
    $accountName,
    $cid,
    $accountType,
    $branchName
);
$pdf->MultiCell(0, 6, $intro);
$pdf->Ln(6);

// Same sentence as your HTML: "The account details and current balance as of the issue date are given below:"
$pdf->Cell(0, 6, 'The account details and current balance as of the issue date are given below:', 0, 1);
$pdf->Ln(5);

// Table style
$pdf->SetFont('Arial', 'B', 11);
$pdf->SetFillColor(230, 230, 230);

// Helper to print one row (label + value)
function cert_kv_row($pdf, $label, $value)
{
    $pdf->SetFont('Arial', 'B', 11);
    $pdf->Cell(60, 8, $label, 1, 0, 'L', true);

    $pdf->SetFont('Arial', '', 11);
    $pdf->Cell(0, 8, $value, 1, 1, 'L');
}

// Rows – same fields as your HTML table
cert_kv_row($pdf, 'Account Holder Name', $accountName);
cert_kv_row($pdf, 'Customer ID (CID)', $cid);
cert_kv_row($pdf, 'Account Number', $accountNo);
cert_kv_row($pdf, 'Account Type', $accountType);
cert_kv_row($pdf, 'Current Balance', number_format($balance, 2) . ' BDT');
cert_kv_row($pdf, 'Branch', $branchName);

// Signature section – “Authorized Officer / My Bank” like footer
$pdf->Ln(14);
$pdf->SetFont('Arial', '', 11);
$pdf->Cell(0, 6, 'For and on behalf of My Bank', 0, 1);

$pdf->Ln(18);
$x = $pdf->GetX();
$y = $pdf->GetY();

// Signature line
$pdf->SetDrawColor(0, 0, 0);
$pdf->Line($x + 10, $y, $x + 70, $y);

$pdf->Ln(4);
$pdf->Cell(0, 6, 'Authorized Officer', 0, 1);

// ------------------------------------------
// 7) Output PDF as download
// ------------------------------------------
$filename = 'certificate-' . preg_replace('/[^0-9A-Za-z_-]/', '', $accountNo) . '.pdf';
$pdf->Output('D', $filename);   // 'D' = force download
exit;
